// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlxPGy1o8huE-Rqt43dafkS02T3K10Dc',
    appId: '1:980395051112:web:12f1cf3397267bb8e9d3dd',
    messagingSenderId: '980395051112',
    projectId: 'tabungan-digital-5d521',
    authDomain: 'tabungan-digital-5d521.firebaseapp.com',
    storageBucket: 'tabungan-digital-5d521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5mteLFnMcSq-Knlsj--63O1jYwNfUNo',
    appId: '1:980395051112:android:b42fffdef544d77de9d3dd',
    messagingSenderId: '980395051112',
    projectId: 'tabungan-digital-5d521',
    storageBucket: 'tabungan-digital-5d521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGTknyCYGEdZKBslsL9ovAWLDSz4XeuQ',
    appId: '1:980395051112:ios:c9d76473c6d5904fe9d3dd',
    messagingSenderId: '980395051112',
    projectId: 'tabungan-digital-5d521',
    storageBucket: 'tabungan-digital-5d521.appspot.com',
    iosClientId: '980395051112-u5a4ng0l3lfbat8ke9vavikdunn39b92.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabunganDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGTknyCYGEdZKBslsL9ovAWLDSz4XeuQ',
    appId: '1:980395051112:ios:c9d76473c6d5904fe9d3dd',
    messagingSenderId: '980395051112',
    projectId: 'tabungan-digital-5d521',
    storageBucket: 'tabungan-digital-5d521.appspot.com',
    iosClientId: '980395051112-u5a4ng0l3lfbat8ke9vavikdunn39b92.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabunganDigital',
  );
}
